image: registry.gitlab.cs.internal.local:5050/phantichchai/instructable-ai-agent/gitlab-ci-image:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: fastapi-gpu-app:latest

build:
  stage: build
  tags:
    - target-lan
  rules:
    - if: '$CI_COMMIT_BRANCH == "deploy"'
      when: always
  script:
    - echo "CI is using custom image"
    - git clone --branch deploy --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cs.internal.local/phantichchai/instructable-ai-agent.git
    - cd instructable-ai-agent
    - dvc remote modify minio access_key_id $AWS_ACCESS_KEY_ID
    - dvc remote modify minio secret_access_key $AWS_SECRET_ACCESS_KEY
    - dvc remote modify minio endpointurl $DVC_ENDPOINT_URL
    - dvc pull saved_models/mineclip/attn_new.pth saved_models/policy/PolicyFromMineCLIP_exp-AllSingleAction_data-ConsistentV2.3_prompt-ACTION_seed-42_epoch301_20250602-041932.pt
    - docker build -t $DOCKER_IMAGE .

deploy:
  stage: deploy
  tags:
    - target-lan
  rules:
    - if: '$CI_COMMIT_BRANCH == "deploy"'
      when: always
  script:
    - echo "Deploying using docker-compose"
    - git clone --branch deploy --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cs.internal.local/phantichchai/instructable-ai-agent.git
    - cd instructable-ai-agent
    - docker compose down
    - docker compose up -d
