version: '3.8'

services:
  fastapi-gpu-app:
    image: fastapi-gpu-app:v0.1.0
    container_name: my-fastapi-gpu-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
